export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const NEWS_ROUTE = '/news'
export const PREW_ROUTE = '/'
export const INSURANCES_ROUTE = '/insurances'
export const REALTY_ROUTE = '/realty'
export const CONTACTS_ROUTE = '/contacts'
